# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-20 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('datafile', models.ImageField(blank=True, null=True, upload_to=events.models.upload_to, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='UserEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('longitude', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=255)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.User', to_field='username')),
            ],
        ),
        migrations.AddField(
            model_name='fileupload',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.UserEvents'),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.User', to_field='username'),
        ),
    ]
