# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userevents',
            name='active',
        ),
        migrations.AddField(
            model_name='userevents',
            name='latitude',
            field=models.FloatField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userevents',
            name='longitude',
            field=models.FloatField(default=' '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userevents',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
