# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-19 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank='True', default='', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('datafile', models.ImageField(blank=True, null=True, upload_to=events.models.upload_to, verbose_name='image')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.UserEvents')),
            ],
        ),
    ]
