# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20160918_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevents',
            name='latitude',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='userevents',
            name='longitude',
            field=models.FloatField(default=1),
        ),
    ]
