# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 00:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20160918_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userevents',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='userevents',
            name='longitude',
        ),
    ]
