# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-20 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=b'True', default=b'', max_length=255)),
                ('username', models.CharField(blank=b'True', default=b'', max_length=255, unique=True)),
                ('user_id', models.BigIntegerField()),
                ('authentication_token', models.CharField(blank=b'True', default=b'', max_length=255)),
            ],
        ),
    ]
